coophcc/email_page/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('email_page.views',
	(r'^(?P<page_type>\w+)/(?P<item_id>\d+)/$', 'email_pdf'),
)

coophcc/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.conf.urls.defaults import *


# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	(r'^admin/', include(admin.site.urls)),
	(r'^contact/', include('contact.urls')),
	(r'^info/', include('info.urls')),
	(r'^news/search/', include('news.search-urls')),
	(r'^news/', include('news.urls')),
	(r'^programs/', include('programs.urls')),
	(r'^jobs/search/', include('job_listings.search-urls')),
	(r'^jobs/', include('job_listings.urls')),
	(r'^accounts/', include('user_management.urls')),
	(r'^search/', include('search.urls')),
	(r'^contact/', include('contact.urls')),
	(r'^email_page/', include('email_page.urls')),
	(r'^$', 'homepage.views.homepage'),
)

coophcc/email_page/models.py
from django.db import models

# Create your models here.

coophcc/email_page/forms.py
from django import forms

class EmailForm(forms.Form):
	subject = forms.CharField(max_length=127)
	message = forms.CharField(widget=forms.Textarea(attrs={'cols': 46, 'rows': 8}))
	sender = forms.EmailField()
	recipients = forms.EmailField()

coophcc/email_page/views.py
from django.shortcuts import render_to_response, HttpResponseRedirect
from django.views.decorators.csrf import csrf_protect
from django.template import RequestContext
from email_page.forms import EmailForm
from django.core.mail import EmailMessage
from news.views import get_news_pdf
from job_listings.views import get_listing_pdf


def email_pdf(request, page_type, item_id):

	if request.method == 'POST': # If the form has been submitted...
		form = EmailForm(request.POST) # A form bound to the POST data

		if form.is_valid(): # All validation rules pass
			subject = form.cleaned_data['subject']
			message = form.cleaned_data['message']
			sender = form.cleaned_data['sender']
			recipients = form.cleaned_data['recipients']

			if page_type == 'news':
				attachment = get_news_pdf(request, item_id)
			elif page_type == 'jobs':
				attachment = get_listing_pdf(request, item_id)
			elif page_type == 'info':
				attachment = get_info_pdf(request, item_id)

			email = EmailMessage(subject, message, sender, [recipients])
			email.attach('attachment', attachment, 'application/pdf')
			email.send()

			if page_type == 'news':
				return HttpResponseRedirect('/news/' + str(news_id) + '/') # Redirect after POST
			elif page_type == 'jobs':
				return HttpResponseRedirect('/jobs/view_listing/' + str(news_id) + '/') # Redirect after POST
			elif page_type == 'info':
				return HttpResponseRedirect('/info/' + str(news_id) + '/') # Redirect after POST

	else:
		form = EmailForm() # An unbound form

	form = EmailForm()

	return render_to_response('email_page/email_pdf.html', {
		'page_type': page_type,
		'item_id': item_id,
		'form': form,
		}, context_instance=RequestContext(request))

coophcc/templates/email_page/email_pdf.html
{% extends 'base.html' %}


{% block body %}
<div class='grid_24'>
	<div style='margin: 5px;'>
		<h1>Send Page By E-mail</h1>

		<form action="/email_page/{{ page_type }}/{{ item_id }}/" method="post">{% csrf_token %}
			{{ form.non_field_errors }}
			<div class="fieldWrapper">
				{{ form.recipients.errors }}
				<p>
				{{ form.recipients }}
				<label for="id_recipients">Email Recipients</label>
				</p>
			</div>
			<div class="fieldWrapper">
				{{ form.sender.errors }}
				<p>
				{{ form.sender }}
				<label for="id_sender">Your Email</label>
				</p>
			</div>
			<div class="fieldWrapper">
				{{ form.subject.errors }}
				<p>
				{{ form.subject }}
				<label for="id_subject">Subject</label>
				</p>
			</div>
			<div class="fieldWrapper">
				{{ form.message.errors }}
				<p>
				{{ form.message }}
				<label for="id_message">Message</label>
				</p>
			</div>
			{% for hidden in form.hidden_fields %}
			{{ hidden }}
			{% endfor %}
			<p><input type="submit" value="Send message" /></p>
		</form>
	</div>
</div>
{% endblock %}