coophcc/job_listings/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('',
	(r'^(?P<degree_program_id>\d+)/(?P<page_number>\d+)/$', 'job_listings.views.job_listings'),
	(r'^create_listing/$', 'job_listings.views.create_job_listing'),
	(r'^edit_listing/(?P<listing_id>\d+)/$', 'job_listings.views.edit_job_listing'),
	(r'^owners_job_listings/(?P<page_number>\d+)/$', 'job_listings.views.owners_job_listings'),
	(r'^contact_poster/(?P<degree_program_id>\d+)/(?P<job_id>\d+)/$', 'job_listings.views.contact_poster'),
	(r'^view_listing/(?P<job_id>\d+)/$','job_listings.views.view_listing'),
	(r'^view_listing/(?P<job_id>\d+)/pdf/$','job_listings.views.get_listing_pdf'),
	(r'^view_owners_listing/(?P<job_id>\d+)/$','job_listings.views.view_owners_listing'),
	(r'^delete_job_listing/(?P<job_id>\d+)/$', 'job_listings.views.delete_job_listing'),
	(r'^search/$', 'search.views.search_listings'),
	(r'^$', 'job_listings.views.job_listing_homepage'),
)

coophcc/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.conf.urls.defaults import *


# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	(r'^admin/', include(admin.site.urls)),
	(r'^contact/', include('contact.urls')),
	(r'^info/', include('info.urls')),
	(r'^news/search/', include('news.search-urls')),
	(r'^news/', include('news.urls')),
	(r'^programs/', include('programs.urls')),
	(r'^jobs/search/', include('job_listings.search-urls')),
	(r'^jobs/', include('job_listings.urls')),
	(r'^accounts/', include('user_management.urls')),
	(r'^search/', include('search.urls')),
	(r'^contact/', include('contact.urls')),
	(r'^email_page/', include('email_page.urls')),
	(r'^$', 'homepage.views.homepage'),
)

coophcc/job_listings/models.py
from django.db import models
from django.contrib.auth.models import User

class HomepageText(models.Model):
	description = models.TextField()

	def __unicode__(self):
		return self.description


class DegreeProgram(models.Model):
	title = models.CharField(max_length=127)

	def __unicode__(self):
		return self.title

	def get_absolute_url(self):
		return '/jobs/' + str(self.id) + '/'


class JobListing(models.Model):
	degree_program = models.ForeignKey('DegreeProgram')
	owner = models.ForeignKey(User)
	title = models.CharField(max_length=127)
	description = models.TextField()
	contact_name = models.CharField(max_length=53, blank=True)
	contact_email = models.EmailField(blank=True)
	contact_phone = models.CharField(max_length=14, blank=True)
	created = models.DateTimeField(auto_now_add=True)
	lastedit = models.DateTimeField(auto_now=True)

	def __unicode__(self):
		return self.title

	def get_absolute_url(self):
		return '/jobs/view_listing/'+ str(self.id) + '/'

coophcc/job_listings/forms.py
from django.forms import ModelForm, HiddenInput, TextInput, Textarea, CharField
from job_listings.models import JobListing
from django import forms

class JobListingForm(ModelForm):
	title = CharField(max_length=127, widget=TextInput(attrs={'size':'75'}))

	class Meta:
		model = JobListing
		widgets = {
			'owner': HiddenInput(),
			'description': Textarea(attrs={'cols': 90, 'rows': 20}),
		}


class PosterContactForm(forms.Form):
    subject = forms.CharField(max_length=127)
    message = forms.CharField(widget=forms.Textarea(attrs={'cols': 46, 'rows': 8}))
    sender = forms.EmailField()

coophcc/search/forms.py
from django.forms import ModelForm, HiddenInput, TextInput, Textarea, CharField, Select
from django import forms
from job_listings.models import DegreeProgram

JOB_SEARCH_CHOICES = [
	['1','one',],
	['1', 'two',],
	['3', 'three',]
	]

class JobSearchForm(forms.Form):

	program = forms.ChoiceField(widget=Select(), choices=JOB_SEARCH_CHOICES)
	q = forms.CharField(label='Search', max_length=127, widget=TextInput(attrs={'size':'75'}))

coophcc/job_listings/views.py
from django.views.decorators.csrf import csrf_protect
from django.http import HttpResponseRedirect
from django.template import RequestContext
from django.shortcuts import render_to_response
from job_listings.models import JobListing, DegreeProgram, HomepageText
from django.contrib.auth.decorators import login_required
from job_listings.forms import JobListingForm, PosterContactForm
from django.contrib.auth.models import User
from homepage.views import render_to_pdf
from django.core.mail import send_mail


def job_listing_homepage(request):
	homepage_text_object = HomepageText.objects.all()[:1]


	return render_to_response('job_listings/jobs_homepage.html', {
		'homepage_text_object': homepage_text_object,
		}, context_instance=RequestContext(request))


def job_listings(request, degree_program_id, page_number):
	degree_program = DegreeProgram.objects.get(pk=degree_program_id)

	total_job_listings = JobListing.objects.filter(degree_program=degree_program_id)
	pages_count = total_job_listings.count()/10
	pages_count = int(pages_count)+1
	pages = []
	for i in range(pages_count):
		pages.append(i+1)

	last_listing = 10*int(page_number)
	first_listing = int(last_listing)-10
	last_listing = int(last_listing)

	try:
		job_listings = JobListing.objects.filter(degree_program=degree_program_id)[first_listing:last_listing]

	except:
		return HttpResponseRedirect('/jobs/')


	return render_to_response('job_listings/jobs.html', {
		'pages': pages,
		'job_listings': job_listings,
		'degree_program': degree_program,
		}, context_instance=RequestContext(request))


#def render_job(request, degree_program_id, job_id):
	#degreeprogram_objects = DegreeProgram.objects.all()

	#try:
		#displayed_object = JobListing.objects.get(pk=job_id)
		#degree_program = DegreeProgram.objects.get(pk=degree_program_id)
		#contact_form = PosterContactForm()

	#except:
		#return HttpResponseRedirect('/jobs/' + str(degree_program_id) + '/')


	#return render_to_response('job_listings/job_listing.html', {
		#'contact_form': contact_form,
		#'degreeprogram_objects': degreeprogram_objects,
		#'displayed_object': displayed_object,
		#'degree_program': degree_program,
		#}, context_instance=RequestContext(request))


def contact_poster(request, degree_program_id, job_id):

	if request.method == 'POST': # If the form has been submitted...
		form = PosterContactForm(request.POST) # A form bound to the POST data
		recipient = JobListing.objects.get(pk=job_id)
		recipient_email = recipient.owner.email

		if form.is_valid(): # All validation rules pass
			subject = form.cleaned_data['subject']
			message = form.cleaned_data['message']
			sender = form.cleaned_data['sender']

			recipients = [recipient_email]

			send_mail(subject, message, sender, recipients)
			return HttpResponseRedirect('/jobs/view_listing/' + ljob_id + '/') # Redirect after POST

	else:
		return HttpResponseRedirect('/jobs/view_listing/' + job_id + '/')


def view_listing(request, job_id):

	try:
		displayed_object = JobListing.objects.get(pk=job_id)
		degree_program = DegreeProgram.objects.get(pk=displayed_object.degree_program.id)
		contact_form = PosterContactForm()

	except:
		return HttpResponseRedirect('/jobs/')


	return render_to_response('job_listings/view_listing.html', {
		'contact_form': contact_form,
		'displayed_object': displayed_object,
		'degree_program': degree_program,
		}, context_instance=RequestContext(request))



@login_required(login_url='/accounts/login/')
def create_job_listing(request):
	if request.method == 'POST':
		request.POST.owner = request.user

		form = JobListingForm(request.POST)

		if form.is_valid(): # All validation rules pass

			form.save()

			return HttpResponseRedirect('/accounts/')

		else:
			return render_to_response('job_listings/create_listing.html', {
			'form': form,
			}, context_instance=RequestContext(request))


	initial = {
		'owner': request.user,
		}
	form = JobListingForm(initial)

	return render_to_response('job_listings/create_listing.html', {
		'form': form,
		}, context_instance=RequestContext(request))


@login_required(login_url='/accounts/login/')
def edit_job_listing(request, listing_id):

	if request.method == 'POST':
		request.POST.owner = request.user

		form = JobListingForm(request.POST)

		if form.is_valid(): # All validation rules pass

			job_object = JobListing.objects.get(pk=listing_id)

			degree_program = form.cleaned_data['degree_program']
			title = form.cleaned_data['title']
			description = form.cleaned_data['description']
			contact_name = form.cleaned_data['contact_name']
			contact_email = form.cleaned_data['contact_email']
			contact_phone = form.cleaned_data['contact_phone']

			job_object.degree_program = degree_program
			job_object.title = title
			job_object.description = description
			job_object.contact_name = contact_name
			job_object.contact_email = contact_email
			job_object.contact_phone = contact_phone

			job_object.save()

			return HttpResponseRedirect('/jobs/view_listing/' + listing_id + '/')

		else:
			return render_to_response('job_listings/edit_listing.html', {
			'form': form,
			}, context_instance=RequestContext(request))

	owner = request.user
	job_object = JobListing.objects.get(pk=listing_id)

	if job_object.owner == owner:

		degree_program = job_object.degree_program
		title = job_object.title
		description = job_object.description
		contact_name = job_object.contact_name
		contact_email = job_object.contact_email
		contact_phone = job_object.contact_phone

		initial = {
			'owner': owner,
			'degree_program': degree_program,
			'title': title,
			'description': description,
			'contact_name': contact_name,
			'contact_email': contact_email,
			'contact_phone': contact_phone,
			}

		form = JobListingForm(initial)
		action_url = '/jobs/edit_listing/' + str(listing_id) + '/'

	else:
		return HttpResponseRedirect('/accounts/')


	return render_to_response('job_listings/edit_listing.html', {
		'action_url': action_url,
		'job_object': job_object,
		'form': form,
		}, context_instance=RequestContext(request))


@login_required(login_url='/accounts/login/')
def owners_job_listings(request, page_number):

	total_job_listings = JobListing.objects.filter(owner=request.user)
	pages_count = total_job_listings.count()/10
	pages_count = int(pages_count)+1
	pages = []
	for i in range(pages_count):
		pages.append(i+1)

	last_listing = 10*int(page_number)
	first_listing = int(last_listing)-10
	last_listing = int(last_listing)

	try:
		job_listings = JobListing.objects.filter(owner=request.user)[first_listing:last_listing]

	except:
		job_listings = []


	return render_to_response('job_listings/owners_job_listings.html', {
		'pages': pages,
		'job_listings': job_listings,
		}, context_instance=RequestContext(request))


def view_owners_listing(request, job_id):

	try:
		displayed_object = JobListing.objects.get(owner=request.user, pk=job_id)
		degree_program = DegreeProgram.objects.get(pk=displayed_object.degree_program.id)
		contact_form = PosterContactForm()

	except:
		return HttpResponseRedirect('/jobs/owners_job_listings/1/')


	return render_to_response('job_listings/view_owners_listing.html', {
		'contact_form': contact_form,
		'displayed_object': displayed_object,
		'degree_program': degree_program,
		}, context_instance=RequestContext(request))


@login_required(login_url='/accounts/login/')
def delete_job_listing(request, job_id):
	job_listing = JobListing.objects.get(pk=job_id, owner=request.user)

	if request.method == 'POST':
		job_listing.delete()

		HttpResponseRedirect('/jobs/owners_job_listings/1/')

	try:
		displayed_object = JobListing.objects.get(pk=job_id)
		degree_program = DegreeProgram.objects.get(pk=job_listing.degree_program.id)
		contact_form = PosterContactForm()

	except:
		return HttpResponseRedirect('/jobs/owners_job_listings/1/')


	return render_to_response('job_listings/delete_job_listings.html', {
		'job_listing': job_listing,
		'contact_form': contact_form,
		'displayed_object': displayed_object,
		'degree_program': degree_program,
		}, context_instance=RequestContext(request))

#
# PDF Views
#
def get_listing_pdf(request, job_id):

	try:
		displayed_object = JobListing.objects.get(pk=job_id)
		degree_program = DegreeProgram.objects.get(pk=displayed_object.degree_program.id)
		contact_form = PosterContactForm()

	except:
		return HttpResponseRedirect('/jobs/')

	context = {
		'contact_form': contact_form,
		'displayed_object': displayed_object,
		'degree_program': degree_program,
		}

	#context = RequestContext(request, content)


	return render_to_pdf('job_listings/view_listing.html',context)

coophcc/templates/job_listings/create_listing.html
{% extends "user_management/admin-sidebar.html" %}

{% block body %}
<div class='grid_19'>
	<div style='margin: 5px;'>
		<h1>Post New Job Listing<hr></h1>

		<form method="post" action="/jobs/create_listing/">
		{% csrf_token %}

		<div class="fieldWrapper">
			<font color='red'>{{ form.degree_program.errors }}</font>
			<p>
			{{ form.degree_program }}
			<label>Degree Program</label>
			</p>
		</div>
		<div class="fieldWrapper">
			<font color='red'>{{ form.contact_name.errors }}</font>
			<p>
			{{ form.contact_name }}
			<label>Contact Name</label>
			</p>
		</div>
		<div class="fieldWrapper">
			<font color='red'>{{ form.contact_email.errors }}</font>
			<p>
			{{ form.contact_email }}
			<label>Contact E-mail</label>
			</p>
		</div>
		<div class="fieldWrapper">
			<font color='red'>{{ form.contact_phone.errors }}</font>
			<p>
			{{ form.contact_phone }}
			<label>Contact Phone</label>
			</p>
		</div>
		</br>
		<hr>
		<div class="fieldWrapper">
			<font color='red'>{{ form.title.errors }}</font>
			<p>
			<label>Title</label>
			{{ form.title }}
			</p>
		</div>
		<div class="fieldWrapper">
			<font color='red'>{{ form.description.errors }}</font>
			<p>
			{{ form.description }}
			</p>
		</div>
		<div class="fieldWrapper">
			<font color='red'>{{ form.owner.errors }}</font>
			<p>
			{{ form.owner }}
			</p>
		</div>

		<input type="submit" value="Submit" />
		<input type="hidden" name="next" value="Submit" />
		</form>

	</div>
</div>
{% endblock %}

coophcc/templates/job_listings/delete_job_listings.html
{% extends "user_management/admin-sidebar.html" %}

{% block body %}
<div class='grid_19'>
	<div style='margin: 5px;'>

		<h1>Job Listings For {{ degree_program }}</h1>
		<form method="post" action="/jobs/delete_job_listing/{{ displayed_object.id }}/">
		{% csrf_token %}
		<h5>
		<font color='red'>Permanently Delete This Listing?</font>
		<input type="submit" value="Yes" />
		<input type="hidden" name="next" value="Submit" />
		</form>
		</h5>
		</br>
		<h3>{{ displayed_object }}<hr></h3>
		<div class='help'>{{ displayed_object.created }}</div>
		<p>{{ displayed_object.description|linebreaks }}</p>
		<h6>Contact<hr></h6>
		<p><b>Name -</b> {{ displayed_object.contact_name }}</p>
		<p><b>Email -</b> {{ displayed_object.contact_email }}</p>
		<p><b>Phone -</b> {{ displayed_object.contact_phone }}</p>

		<p><hr>Last Edited - {{ displayed_object.lastedit }}</p>

	</div>
</div>
{% endblock %}

coophcc/templates/job_listings/edit_listing.html
{% extends "user_management/admin-sidebar.html" %}

{% block body %}
<div class='grid_19'>
	<div style='margin: 5px;'>
		<h1>Edit Job Listing<hr></h1>

		<form method="post" action={{ action_url }}>
		{% csrf_token %}

		<div class="fieldWrapper">
			<font color='red'>{{ form.degree_program.errors }}</font>
			<p>
			{{ form.degree_program }}
			<label>Degree Program</label>
			</p>
		</div>
		<div class="fieldWrapper">
			<font color='red'>{{ form.contact_name.errors }}</font>
			<p>
			{{ form.contact_name }}
			<label>Contact Name</label>
			</p>
		</div>
		<div class="fieldWrapper">
			<font color='red'>{{ form.contact_email.errors }}</font>
			<p>
			{{ form.contact_email }}
			<label>Contact E-mail</label>
			</p>
		</div>
		<div class="fieldWrapper">
			<font color='red'>{{ form.contact_phone.errors }}</font>
			<p>
			{{ form.contact_phone }}
			<label>Contact Phone</label>
			</p>
		</div>
		</br>
		<hr>
		<div class="fieldWrapper">
			<font color='red'>{{ form.title.errors }}</font>
			<p>
			<label>Title</label>
			{{ form.title }}
			</p>
		</div>
		<div class="fieldWrapper">
			<font color='red'>{{ form.description.errors }}</font>
			<p>
			{{ form.description }}
			</p>
		</div>
		<div class="fieldWrapper">
			<font color='red'>{{ form.owner.errors }}</font>
			<p>
			{{ form.owner }}
			</p>
		</div>

		<input type="submit" value="Submit" />
		<input type="hidden" name="next" value="Submit" />
		</form>

	</div>
</div>
{% endblock %}

coophcc/templates/job_listings/job_listing.html
{% extends "base.html" %}


{% block sidebar %}
<div class='sidebar'>
	<div style='margin: 5px;'>
	<h5>Degree Programs</h5>
	{% for i in degreeprogram_objects %}
	<a href='{{ i.get_absolute_url }}1/'><font color='blue'><u>{{ i }}</u></font></a>
	{% endfor %}
	</br>
	</br>
	<a href='/jobs/view_listing/{{ displayed_object.id }}/pdf/' style='font: 12px/1.5 sans-serif;'><image src='/static/media/image/pdf_icon.gif'/> <u>PDF version</u></a>
	</div>
</div>
</br>
{% endblock %}

{% block body %}
<div class='grid_19'>
	<div style='margin: 5px;'>

		<h1>Job Listings For {{ degree_program }}</h1>
		<h3>{{ displayed_object }}<hr></h3>
		<div class='help'>{{ displayed_object.created }}</div>
		<p>{{ displayed_object.description|linebreaks }}</p>
		<h6>Contact<hr></h6>
		<p><b>Name -</b> {{ displayed_object.contact_name }}</p>
		<p><b>Email -</b> {{ displayed_object.contact_email }}</p>
		<p><b>Phone -</b> {{ displayed_object.contact_phone }}</p>


		<form action="/jobs/contact_poster/{{ displayed_object.degree_program.id }}/{{ displayed_object.id }}/" method="post">{% csrf_token %}
			{{ contact_form.non_field_errors }}
			<div class="fieldWrapper">
				<font color='red'>{{ contact_form.sender.errors }}</font>
				<p>
				{{ contact_form.sender }}
				<label>Your E-mail</label>
				</p>
			</div>
			<div class="fieldWrapper">
				<font color='red'>{{ contact_form.subject.errors }}</font>
				<p>
				{{ contact_form.subject }}
				<label>Subject</label>
				</p>
			</div>
			<div class="fieldWrapper">
				<font color='red'>{{ contact_form.message.errors }}</font>
				<p>
				{{ contact_form.message }}
				</p>
			</div>
			<p><input type="submit" value="Send E-mail" /></p>
		</form>

		<p><hr>Last Edited - {{ displayed_object.lastedit }}</p>

	</div>
</div>
{% endblock %}

coophcc/templates/job_listings/jobs-sidebar.html
{% extends "base.html" %}


{% block sidebar %}
<div class='grid_5'>
	<div class='sidebar'>
		<div style='margin: 5px;'>
			<h5>Additional Links</h5>
			<a href='/jobs/search/' style='font: 12px/1.5 sans-serif;><u><font color='#007c85'><u>Job Search</u></a>
			</br></br>
			<font color='#007c85'><b>Search By Degree</b></font></br>
			{% for i in degreeprogram_objects %}
			<a href='/jobs/search/?q={{ i.title|lower }}&models=job_listings.joblisting'><font color='blue'><u>{{ i }}</u></font></a>
			{% endfor %}
			</br>
			</br>
			<a href='/email_page/jobs/{{ displayed_object.id }}/' style='font: 12px/1.5 sans-serif;'>
			<image src='/static/media/image/mail_icon.gif'/>
			<u> Send to friend</u>
			</a>
			</br>
			<a href='/jobs/view_listing/{{ displayed_object.id }}/pdf/' style='font: 12px/1.5 sans-serif;'>
			<image src='/static/media/image/pdf_icon.gif'/>
			<u> PDF version</u>
			</a>
		</div>
	</div>
</br>
</div>
{% endblock %}

coophcc/templates/job_listings/jobs.html
{% extends "job_listings/jobs-sidebar.html" %}

{% block body %}
<div class='grid_19'>
	<div class='serch_link' style='margin: 5px;'>
		<h1>Job Listings For {{ degree_program }}</h1>
		<ol>
		{% for i in job_listings %}
		<li><a href='/jobs/view_listing/{{ i.id }}'><b><font color='black'>{{ i }}</b></font></br><font color='black'>{{ i.description|truncatewords:30 }} - </font><font color='#007c85'>{{ i.created }}</font></a></li>
		</br></br>
		{% endfor %}
		</ol>

		<p>Page:
		{% for i in pages %}
			<a href='/jobs/{{ degree_program.id }}/{{ i }}/'>{{ i }}</a> ,
		{% endfor %}
		</p>

	</div>
</div>
{% endblock %}

coophcc/templates/job_listings/jobs_homepage.html
{% extends "job_listings/jobs-sidebar.html" %}

{% block body %}
<div class='grid_19'>
	<div style='margin: 5px;'>

		{% if displayed_object %}
			<h1></h1>
			<p>{{ displayed_object }}</p>
		{% endif %}

		<h2>Job Search</h2>

		<form method="get" action="/jobs/search">
			<table>
				<input type="submit" value="Search" size="100">
				<input type="text" name="q" value="" id="id_q" size='80'/>
				<input type="hidden" name="models" value="job_listings.joblisting" id="id_models_0" />
			</table>

			{% if query %}
			<h3>Results</h3>

			<ol>
			{% for result in page.object_list %}

					<li>
						<a href="{{ result.object.get_absolute_url }}">
						<b><font color='#007c85'>{{ result.object.degree_program }} : </font><font color='black'>{{ result.object.title }}</b></font>
						</br>
						<font color='black'>{{ result.object.description|truncatewords:30 }} - </font>
						<font color='#007c85'>{{ result.object.created }}</font>
						</a>
					</li>
			{% empty %}
					<p>No results found.</p>
			{% endfor %}
			</ol>

			{% if page.has_previous or page.has_next %}
					<div>
			{% if page.has_previous %}<a href="?q={{ query }}&amp;page={{ page.previous_page_number }}">{% endif %}&laquo; Previous{% if page.has_previous %}</a>{% endif %}
				|
			{% if page.has_next %}<a href="?q={{ query }}&amp;page={{ page.next_page_number }}">{% endif %}Next &raquo;{% if page.has_next %}</a>{% endif %}
					</div>
			{% endif %}
			{% else %}
					{# Show some example queries to run, maybe query syntax, something else? #}
			{% endif %}
		</form>

	</div>
</div>
{% endblock %}

coophcc/templates/job_listings/owners_job_listings.html
{% extends "user_management/admin-sidebar.html" %}

{% block body %}
<div class='grid_19'>
	<div class='serch_link' style='margin: 5px;'>
		<h1>Your Job Listings</h1>
		<ol>
		{% for i in job_listings %}
		<li><a href='/jobs/edit_listing/{{ i.id }}/'><font color='green'><b>Edit</b></font></a>
		|
		<a href='/jobs/delete_job_listing/{{ i.id }}/'><font color='red'><b>Delete</b></font></a>

		<a href='/jobs/view_owners_listing/{{ i.id }}/'><font color='blue'></font> - <b><font color='black'>{{ i }}</b></br>{{ i.description|truncatewords:30 }}</font> - <font color='#007c85'>{{ i.created }}</font></a></li>
		</br>
		{% endfor %}
		</ol>

		<p>Page:
		{% for i in pages %}
			<a href='/jobs/owners_job_listings/{{ i }}/'>{{ i }}</a> ,
		{% endfor %}
		</p>

	</div>
</div>
{% endblock %}

coophcc/templates/job_listings/search_listings.html
{% extends "job_listings/jobs-sidebar.html" %}


{% block body %}
<div class='grid_19'>
	<div style='margin: 5px;'>
		<h2>Job Search</h2>

		<form method="get" action=".">
			<table>
				<input type="submit" value="Search" size="100">
				<input type="text" name="q" value="" id="id_q" size='80'/>
				<input type="hidden" name="models" value="job_listings.joblisting" id="id_models_0" />
			</table>

			{% if query %}
			<h3>Results</h3>

			<ol>
			{% for result in page.object_list reversed %}

					<li>
						<a href="{{ result.object.get_absolute_url }}">
						<b><font color='#007c85'>{{ result.object.degree_program }} : </font><font color='black'>{{ result.object.title }}</b></font>
						</br>
						<font color='black'>{{ result.object.description|truncatewords:30 }} - </font>
						<font color='#007c85'>{{ result.object.created }}</font>
						</a>
					</li>
			{% empty %}
					<p>No results found.</p>
			{% endfor %}
			</ol>

			{% if page.has_previous or page.has_next %}
					<div>
			{% if page.has_previous %}<a href="?q={{ query }}&amp;page={{ page.previous_page_number }}">{% endif %}&laquo; Previous{% if page.has_previous %}</a>{% endif %}
				|
			{% if page.has_next %}<a href="?q={{ query }}&amp;page={{ page.next_page_number }}">{% endif %}Next &raquo;{% if page.has_next %}</a>{% endif %}
					</div>
			{% endif %}
			{% else %}
					{# Show some example queries to run, maybe query syntax, something else? #}
			{% endif %}
		</form>
	</div>
</div>
{% endblock %}

coophcc/templates/job_listings/view_listing.html
{% extends "job_listings/jobs-sidebar.html" %}

{% block body %}
<div class='grid_19'>
	<div style='margin: 5px;'>

		<h1>Job Listings For {{ degree_program }}</h1>
		<h3>{{ displayed_object }}<hr></h3>
		<div class='help'>{{ displayed_object.created }}</div>
		<p>{{ displayed_object.description|linebreaks }}</p>
		<h6>Contact<hr></h6>
		<p><b>Name -</b> {{ displayed_object.contact_name }}</p>
		<p><b>Email -</b> {{ displayed_object.contact_email }}</p>
		<p><b>Phone -</b> {{ displayed_object.contact_phone }}</p>


		<form action="/jobs/contact_poster/{{ displayed_object.degree_program.id }}/{{ displayed_object.id }}/" method="post">{% csrf_token %}
			{{ contact_form.non_field_errors }}
			<div class="fieldWrapper">
				<font color='red'>{{ contact_form.sender.errors }}</font>
				<p>
				{{ contact_form.sender }}
				<label>Your E-mail</label>
				</p>
			</div>
			<div class="fieldWrapper">
				<font color='red'>{{ contact_form.subject.errors }}</font>
				<p>
				{{ contact_form.subject }}
				<label>Subject</label>
				</p>
			</div>
			<div class="fieldWrapper">
				<font color='red'>{{ contact_form.message.errors }}</font>
				<p>
				{{ contact_form.message }}
				</p>
			</div>
			<p><input type="submit" value="Send E-mail" /></p>
		</form>

		<p><hr>Last Edited - {{ displayed_object.lastedit }}</p>

	</div>
</div>
{% endblock %}